[package]
name = "warg-crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
sha2 = "0.10"
digest = "0.10"
hex = "0.4"

thiserror = "1.0"
anyhow = "1.0"