[package]
name = "warg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "0.10.3"
sha2 = "0.10.2"

hashbrown = "0.12.3"

base64 = "0.13.0"

prost = "0.10"
# Only necessary if using Protobuf well-known types:
prost-types = "0.10"

[build-dependencies]
prost-build = { version = "0.10" }