[package]
name = "warg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
hashbrown = "0.12"

prost = "0.10"
prost-types = "0.10"

base64 = "0.13.0"
semver = "1.0"

p256 = "0.11"
secrecy = "0.8"
signature = "1.5"
digest = "0.10"
sha2 = "0.10"

[dev-dependencies]
rand_core = { version = "0.6", features = ["getrandom"]}
pretty_assertions = "1.1.0"

[build-dependencies]
prost-build = { version = "0.10" }