/// An example world for the component to target.
interface storage {
  record content {
    log-root: string,
    log-length: u32,
    map-root: string
  }
  record checkpoint {
    contents: content,
    key-id: string,
    signature: string
  }
  store-registry-info: func(input: string)
  get-registry-info: func() -> string
  get-checkpoint: func() -> checkpoint
  hash-checkpoint: func(input: checkpoint) -> string
}                

default world component {
  export reg: interface {
    hello-world: func() -> string
    passthrough: func() -> string
    get-registry-pass: func() -> string
    update: func()
  }
  import storage: self.storage
}                
