[package]
name = "warg-api"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }

[dependencies]
warg-protocol = { workspace = true }
warg-crypto = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
indexmap = { workspace = true }
thiserror = { workspace = true }
