[package]
name = "warg-transparency"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }

[dependencies]
warg-crypto = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
pbjson = { workspace = true }
pbjson-types = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
pbjson-build = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
ciborium = { workspace = true }
criterion = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }

[[bench]]
name = "map"
harness = false

[[bench]]
name = "log"
harness = false
